Finish Mobile version
godybuoy/setup-and-mobile-first-project pull request #2
Opened 2023-01-12 22:33 UTC by godybuoy

Things done;
1. Add styles.css.
2. Add index.html.
3. Add work and contact form for the project.

2023-01-12 22:43 UTC, godybuoy commented
Things done;
1.Add files to index.html
2.Add files to styles.css
3.Configured linters

2023-01-12 22:54 UTC, vickymarz requested changes
Hi @godybuoy, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not contain the `future features` and `license` sections in your readme. KIndly add at least two future features you will add to your project in the future and also add the MIT license as well.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-14 12:58 UTC, godybuoy commented
Things done;
1. Add license to README file.
2. Remove duplicated files in styles.css.
3. Add index.html files.
4. Configured linters.

2023-01-14 13:19 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @godybuoy  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] This logo is a broken link, to make your README file more professional, kindly make sure you fix it :+1: 


![Screenshot from 2023-01-14 15-19-02](https://user-images.githubusercontent.com/80458199/212473596-77b8c9ea-60df-4286-b0cf-4f8b6a7c244c.png)

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 13:19 UTC, iambenkis commented on index.html
> +
- [ ] I acknowledge your great work @godybuoy :+1: , adding this beautiful button on each project , however you should add button styling :active, :hover, and pressed on them , it will improve the user experience , kindly add this property on each button in your project :100: 

![Screenshot from 2023-01-14 15-09-21 (1)](https://user-images.githubusercontent.com/80458199/212473150-80989769-af77-4d83-a97c-9851d4560392.png)

2023-01-14 13:19 UTC, iambenkis commented on index.html
> +<div class="item">
- [ ] Kindly change this button right in the **about section**, It should be `Get my resume` not `See project`.

|Your Design | Figma design|
| :---: | :---: |
|![Screenshot from 2023-01-14 15-10-23](https://user-images.githubusercontent.com/80458199/212473360-6c95fb66-0d37-449c-a37f-a1ce0943616b.png) | ![Screenshot from 2023-01-14 15-12-08](https://user-images.githubusercontent.com/80458199/212473312-3246e739-0f7f-48a4-8496-185489dfc1a8.png) |

2023-01-14 13:19 UTC, iambenkis commented on index.html
> +    <li class="item1"><a href=""><img src="./image/Vector (3).svg" alt=""></a></li>
- [ ] You should attach your personal social media link to this `a` tags to make it more responsive :+1: 

![Screenshot from 2023-01-14 15-15-37](https://user-images.githubusercontent.com/80458199/212473457-b1e9320e-0eae-43c8-8cb6-79735f20167f.png)

2023-01-14 14:03 UTC, godybuoy commented
Things done;

1.Add license to README file.
2.Fix about button.
3.Configured linters.

2023-01-14 14:16 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @godybuoy,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 14:16 UTC, merged