Desktop version
godybuoy/setup-and-mobile-first-project pull request #4
Opened 2023-01-19 19:47 UTC by godybuoy

Things done;
1. Add desktop header.
2. Add desktop footer.
3. configured linters.

2023-01-19 20:01 UTC, BregornOriginal requested changes
## Hi @godybuoy  

## Good job so far!

## There are some issues that you still need to work on to go to the next project but you are almost there!

![cat-driving-serious](https://user-images.githubusercontent.com/93630700/213547464-3bf0fec2-c394-42f2-bf97-350c46c2e368.gif)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Your designs look very good! 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 19:39 UTC, godybuoy commented
Things done;
1.Update about and skills section.
2.Update contact footer background image.
3.Fix form section.
4.Fix skill section.
4.Configured linters.

2023-01-20 20:24 UTC, BregornOriginal requested changes
## Hi @godybuoy  

## Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✅ Linters are passing
✅ Good commit history

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 20:24 UTC, BregornOriginal commented on styles.css
> +
- [ ] Kindly check your about and skills sections, when I'm up to 1500px wide, the skills sections are going to hide back to the form section, try removing your top property in your contact class selector 🥇 

![image](https://user-images.githubusercontent.com/93630700/213546363-550a1761-628b-45f0-8134-faa69a3bafcc.png)

2023-01-20 21:22 UTC, godybuoy commented
Things done;
1. Fix about and skills section to make it responsive.
2. Configured linters.

2023-01-21 01:21 UTC, franclobo approved these changes
Hi @godybuoy, 

# STATUS: APPROVED 😃 

![gif-good-job-79](https://user-images.githubusercontent.com/58642949/213831776-bc782921-ad94-4c10-b891-a924d1b7ce72.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 01:21 UTC, franclobo commented on styles.css
> +  }
- **[ OPTIONAL ]** Kindly add the margins around the section and the border radius at the right top to be similar to the Figma design 👇🏽 

| Figma design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/213831662-f8f8f018-193e-4ee5-8db4-89fd13bd5bda.png) | ![image](https://user-images.githubusercontent.com/58642949/213831685-a39615d5-c0cc-46de-ab51-c89a22dff9d2.png) |

2023-01-23 21:28 UTC, merged